In [3]:
import torch

z = torch.zeros(5,3)
print(z)
print(z.dtype)

i = torch.ones((5,3), dtype = torch.int16)
print(i)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [4]:
# PyTorch 버전 확인
import torch
torch.__version__

'2.7.1+cu126'

이미지 모양을 가진 텐서 [colour_channels, height, width]
 # [3,224,224] 3색상 채널(빨강,초록,파랑), 픽셀 높이 224, 픽셀 너비 224

In [12]:
#스칼라는 단일 숫자, 텐서로는 차원이 0인 텐서
# Scalar
scalar = torch.tensor(7)
print(scalar)

# 스칼라 차원 확인
print(scalar.ndim) 

# torch.Tensor형에서 파이썬 정수형으로
print(type(scalar))
print(scalar.item())

tensor(7)
0
<class 'torch.Tensor'>
7


In [16]:
# Vector
vector = torch.tensor([7,7])
print(vector)

# 벡터의 차원수 확인
print(vector.ndim)

# 벡터의 shape 확인
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [24]:
# Matrix(행렬)
MATRIX = torch.tensor([[7,8],[9,10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [26]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,8],[2,4,5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 8],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


vector와 scalar에는 주로 소문자 사용
MATRIX와 TENSOR에는 주로 대문자 사용
scalar - lower(a)
vector - lower(y)
matrix - upper(Q)
tensor - Upper(X)

In [35]:
# 난수 텐서 생성  # torch.rand()
random_tensor = torch.rand(size=(3,4))
print(random_tensor)
print(random_tensor.dtype)

print()
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224,224,3))
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

tensor([[0.8182, 0.8936, 0.2054, 0.0930],
        [0.8862, 0.9924, 0.3033, 0.5939],
        [0.6800, 0.9944, 0.1413, 0.6854]])
torch.float32

torch.Size([224, 224, 3])
3


In [39]:
# 마스킹(masking), 한 텐서의 일부 값을 0으로 마스킹하여 모델이 해당 값을 학습하지 않도록 함

# torch.zeros()
zeros = torch.zeros(size=(3,4))
print(zeros)
print(zeros.dtype)

print()
# torch.ones
ones = torch.ones(size=(3,4))
print(ones)
print(ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


In [47]:
# torch.arrange(start, end, step)
zero_to_ten = torch.arange(start = 0, end=10, step=1)
print(zero_to_ten)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [48]:
# torch.range() is deprecated(사용중단 됨)
zero_to_ten_deprecated = torch.range(0,10)

C:\Users\hyun\AppData\Local\Temp\ipykernel_18648\2061090737.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0,10)


In [ ]:
# 32-bit floating point(32비트 부동 소수점) : 가장 일반적인 타입 torch.float32 or torch.float
# 특정 데이터 유형을 가진 텐서  #텐서의 기본 데이터 유형은 float32
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device = None, requires_grad=False)
# dtype - dtype을 지정하지 않으면 기본값은 None, 또는 전달되는 데이터 타입을 따름
# device - device를 지정하지 않으면 기본값은 None, default tensor type을 사용함    # default tensor type : torch.tensor([1.0,2.0]) <- torch.tensor([1.0,2.0], dtype=torch.float32, device='cpu')
# requires_grad - True로 설정하면, 텐서에 수행되는 연산들이 기록되어 자동 미분에 사용됨
print(float_32_tensor.shape)
print(float_32_tensor.dtype)
print(float_32_tensor.device)

torch.Size([3])
torch.float32
cpu


모양 문제(tensor shape이 일치하지 않음)를 제외하고 PyTorch에서 가장 일반적으로 접하게 되는 문제가 데이터 유형(datatype), 장치(device) 문제
pytorch는 (often) 텐서들이 같은 format이길 선호함
pytorch는 텐서간의 연산에 있어서 같은 device이길 선호함


In [53]:
flaot_16_tensor = torch.tensor([3.0,6.0,9.0], dtype = torch.float16)  # torch.half를 써도 됨 torch.float16과 동일한 데이터 타입임
float_half_tensor = torch.tensor([3.0,6.0,9.0], dtype = torch.half)
print(flaot_16_tensor.dtype)
print(float_half_tensor.dtype)

torch.float16
torch.float16


In [ ]:
some_tensor = torch.rand(3,4)

print(some_tensor)
print("Shape of tensor :", some_tensor.shape)
print("Datatype of tensor :", some_tensor.dtype)
print("Device tensor is stored on :", some_tensor.device)

# pyTorch에서 issue가 발생하는 경우 위 세 가지 속성 중 하나와 연관된 경우가 많음

tensor([[0.5183, 0.0397, 0.4231, 0.1655],
        [0.5160, 0.3875, 0.4572, 0.4432],
        [0.6420, 0.1925, 0.9964, 0.6856]])
Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on : cpu


딥러닝에서는 데이터(이미지, 텍스트, 비디오, 오디오, 단백질 구조 등)가 tensors로 나타남
model은 그러한 tensors들을 조사하고, 일련의 연산(operations)들을 수행하여 input data의 패턴의 표현(representation)을 학습함
연산(oprations) : 덧셈, 뺄셈, 곱셈(요소간의), 나눗셈, 행렬 곱셈


In [65]:
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor * 10)
print(tensor,"\n")

tensor -= 10 #재할당(reassigned)
print(tensor)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([1, 2, 3]) 

tensor([-9, -8, -7])


In [ ]:
tensor = torch.tensor([1,2,3])
print(torch.multiply(tensor,10))  
print(tensor)
print(tensor*10) # torch.mul 대신 연산자 기호(*)를 사용하는 것이 일반적


tensor([10, 20, 30])
tensor([1, 2, 3])
tensor([10, 20, 30])


In [ ]:
#행렬 곱셈, torch.matmul()
#규칙1. inner demension이 일치해야함
#규칙2. 결과 matrix는 outer dimensions의 shape을 가짐
# 파이썬에서 @는 행렬곱을 나타내는 기호

import torch
tensor = torch.tensor([1,2,3])
print(tensor.shape,"\n")

print(tensor*tensor)
print(tensor.matmul(tensor))
print(tensor@tensor,"\n")

torch.Size([3]) 

tensor([1, 4, 9])
tensor(14)
tensor(14) 

tensor(14)


In [75]:
%%time
#Matrix multiplication by hand (추천되지 않음)
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 15.6 ms
Wall time: 999 μs


In [76]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [ ]:
# 딥러닝에서 가장 흔하게 일어나는 에러
tensor_A = torch.tensor([[1,2],[3,4],[5,6]], dtype = torch.float32)
tensor_B = torch.tensor([[7,10],[8,11],[9,12]], dtype = torch.float32)
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [87]:
#위 텐서들을 transpose(전치)를 통해서 행렬곱을 되게 할 수 있음
#torch.transpose(input, dim0, dim1)
#tensor.T
print(tensor_A)
print(tensor_B.T)

print(tensor_A.shape, tensor_B.T.shape)
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(output.shape)

# torch.mm - matmul의 약자
print(torch.mm(tensor_A,tensor_B.T))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([3, 2]) torch.Size([2, 3])
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
torch.Size([3, 3])
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [96]:
# 행렬 곱셈은 두 행렬간의 내적(dot product)라고도 함
# 신경망은 행렬곱과 내적으로 구성됨(are full of)
# torch.nn.Linear()모듈은 feed-foward layer 또는 fully connected layer로 알려져 있으며, 입력(input) x와 가중치 행렬(weight matrix) A간의 행렬곱을 구현함
## x는 layer에 대한 input, A는 layer에 의해 생성된(created) weight matrix <- 이 행렬은 처음에는 무작위 숫자로 시작하지만, 신경망이 데이터 속 패턴을 더 잘 표현하도록 학습하면서 점점 조정됨
## b는 입력과 가중치에 약간의 변화를 주기 위해 사용된는 편향(bias)

# 위와 같은 것들이 선형 함수(linear function)
torch.manual_seed(42) #linear layer는 랜덤 가중치 행렬로 시작하므로, 결과가 매번 같도록 재현 가능(reproducible)하게 설정/난수 생성기의 시드를 42로 고정하여, 무작위 값들이 항상 동일하게 생성되도록 함

linear = torch.nn.Linear(in_features=2, out_features=6)
x= tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOuput Shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Ouput Shape: torch.Size([3, 6])
