In [ ]:
import torch
tensor_A = torch.tensor([[1,2], [3,4], [5,6]], dtype=torch.float32)
#tensor_B = torch.tensor([[7,10],[8,11],[9,12]], dtype=torch.float32)

torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [21]:
x = torch.arange(0,100,10)
print(x)
print(x.dtype)

print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}") # float datatype이 아니면 작동하지 않음  # x.mean() <- error
print(f"Sum: {x.sum()}\n")

print(torch.max(x))
print(torch.min(x))
print(torch.mean(x.type(torch.float32)))
print(torch.sum(x))

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.int64
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450

tensor(90)
tensor(0)
tensor(45.)
tensor(450)


In [23]:
# torch.argmax(), torch.argmin() <- 각각 최대값, 최소값의 인덱스를 반환  (softmax activation function(활성화함수)을 사용할 때 유용함)
tensor = torch.arange(10,100,10)
print(f"Tensor: {tensor}")
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [26]:
# torch.Tensor.type(dtype=None)을 사용하면 텐서의 자료형 변경 가능, dtype 매개변수는 사용자가 원하는 자료형을 지정
# 텐서를 생성했을 때 기본 데이터타입은 torch.float32
tensor = torch.arange(10.,100.,10.)
print(tensor.dtype)

tensor_float16 = tensor.type(torch.float16)
print(tensor_float16)

tensor_int8 = tensor_float16.type(torch.int8)
print(tensor_int8)

torch.float32
tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)
tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)


In [ ]:
# 실제 값을 바꾸지 않으면서 텐서들의 차원을 바꾸고자 할 때 (change or reshape)
# reshaping, stacking, squeezing and unsqueezing
# torch.reshape(input, shape)  #input을 원하는 형태(shape)으로 재배열
# Tensor.view(shape)  # 기존 텐서의 데이터를 유지하면서 다른 모양의 뷰를 반환   # 다른 모양의 뷰 : 기존 텐서의 메모리를 그대로 사용하면서 shape만 바꾼 텐서
# torch.stack(tensors, dim=0)  # 같은 크기의 텐서들을 새로운 차원으로 쌓음
# torch.squeeze(input)  # 텐서의 모든 크기 1인 차원을 제거
# torch.unsqueeze(input, dim)  # 지정한 위치 dim에 크기 1인 새로운 차원을 추가
# torch.permute(input, dims)  # 텐서의 차원 순서를 바꿈(재배열)

# torch.unsqueeze()
x = torch.tensor([1, 2, 3])  # shape: (3,)
print(x.shape)
print(x,"\n")

unsqueezed = torch.unsqueeze(x, 0)  # 0번 차원에 1 추가 → (1, 3)
print(unsqueezed.shape) 
print(unsqueezed,"\n")

unsqueezed = torch.unsqueeze(unsqueezed, 1)  # 1번 차원에 1 추가 → (3, 1)
print(unsqueezed.shape)
print(unsqueezed)

# torch.permute()
x = torch.randn(2, 3, 4)  # shape: (2, 3, 4)
print(x)
print(x.shape)

permuted = torch.permute(x, (1, 0, 2))  # → (3, 2, 4)
print(permuted)
print(permuted.shape)

torch.Size([3])
tensor([1, 2, 3]) 

torch.Size([1, 3])
tensor([[1, 2, 3]]) 

torch.Size([1, 1, 3])
tensor([[[1, 2, 3]]])


In [60]:
import torch
x = torch.arange(1.,8.)
print(x)
print(x.shape)



tensor([1., 2., 3., 4., 5., 6., 7.])
torch.Size([7])


In [61]:
x_reshaped = x.reshape(1,7)
print(x_reshaped, x_reshaped.shape)

tensor([[1., 2., 3., 4., 5., 6., 7.]]) torch.Size([1, 7])


In [ ]:
z = x.view(1,7) # 다른 모양의 뷰 : 기존 텐서의 메모리를 그대로 사용하면서 shape만 바꾼 텐서
print(z, z.shape)

tensor([[1., 2., 3., 4., 5., 6., 7.]]) torch.Size([1, 7])


In [ ]:
z[:,0]=5  # 기존 텐서의 메모리를 그대로 사용하기 때문에 z를 빠구면 x(original)도 바뀜
print(z,x)

tensor([[5., 2., 3., 4., 5., 6., 7.]]) tensor([5., 2., 3., 4., 5., 6., 7.])


In [ ]:
print(x)
print(x.shape,"\n")

x_stacked = torch.stack([x,x,x,x], dim=0) #dim은 새로운 차원을 어느 인덱스에 넣을지
print(x_stacked)
print(x_stacked.shape,"\n")

x_stacked = torch.stack([x,x,x,x], dim=1)
print(x_stacked)
print(x_stacked.shape)


tensor([5., 2., 3., 4., 5., 6., 7.])
torch.Size([7]) 

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])
torch.Size([4, 7]) 

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])
torch.Size([7, 4])


In [81]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# x_reshaped에서 추가 차원(extra demension) 제거
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [82]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# 추가 차원(extra dimension) 추가
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [84]:
# torch.permute()를 사용하면 axes(축)의 순서를 바꿀 수 있음, 이 함수는 input텐서를 새로운 축 순서를 갖는 뷰(view)로 변환
x_original = torch.rand(size=(224,224,3))

x_permuted = x_original.permute(2,0,1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [95]:
# indexing (selecting data from tensors), 텐서로부터 특정 데이터만 선택하기를 원할 때
import torch
x= torch.arange(1,10).reshape(1,3,3)
print(x, x.shape,"\n")

print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}\n")

# 콜론(:)을 사용하면 해당 차원의 모든 값을 지정할 수 있고, 그 뒤에 쉼표를 사용해서 다른 차원의 값을 추가로 지정 가능
print(x[:,0])
print(x[:,:,1])
print(x[:,1,1])
print(x[0,0,:])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3]) 

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


In [109]:
#PyTorch tensors & Numpy
# torch.from_numpy(ndarray) - Numpy array -> Pytorch tensor
# torch.Tensor.numpy()- Pytorch tensor -> Numpy array
import torch
import numpy as np
array = np.arange(1.0,8.0)  
tensor = torch.from_numpy(array) 
print(array)
print(tensor)
# numpy arrays는 default로 데이터타입이 float64임, pytorch tensor로 바꿔도 데이터 타입이 동일하게 유지됨  
# pytorch 계산은 default로 flaot32를 사용함
# Numpy array -> pytorch tensor(float32) : torch.from_numpy(array).type(torch.float32)

[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [112]:
array = array + 1
#tensor = tensor +1
print(array)
print(tensor)

[2. 3. 4. 5. 6. 7. 8.]
tensor([1., 1., 1., 1., 1., 1., 1.])


In [113]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(tensor)
print(numpy_tensor, numpy_tensor.dtype, "\n")

tensor = tensor+1
print(tensor)
print(numpy_tensor)

tensor([1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1.] float32 

tensor([2., 2., 2., 2., 2., 2., 2.])
[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# 재현 가능성 Reproducibility
